title: Alice Nguyen
#logo: /assets/img/headshot_circle.png
description: Data Analyst | Python | R | SQL | Machine Learning | Artificial Intelligence | Deep Learning | Tableau | Power BI | Business Analyst
show_downloads: true
theme: jekyll-theme-minimal
